Repository kyma-project/eventing-manager, pull requests merged in 2023-12, with the labels that each got.

#284 Add make target to clean the go test cache
  .gitignore
  Makefile
Labels: size/XS, lgtm, area/eventing, cla: yes

#289 Bump version for rel 0.0.0
  .version
  sec-scanners-config.yaml
Labels: size/XS, lgtm, area/ci, cla: yes

#292 bump the eventing-manager version.
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#295 Improve Prow job verification script
  scripts/verify-status.sh
Labels: lgtm, size/S, cla: yes

#286 Update UI with improved notifications
  config/samples/empty_backend.yaml
  config/ui-extensions/eventing/details
  config/ui-extensions/eventing/form
  config/ui-extensions/eventing/kustomization.yaml
Labels: size/M, lgtm, area/eventing, cla: yes

#301 Bump em image
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#308 add codeowners
  CODEOWNERS
Labels: size/XS, lgtm, cla: yes

#283 Add publisher service in the Eventing CR status
  api/operator/v1alpha1/eventing_types.go
  api/operator/v1alpha1/status.go
  api/operator/v1alpha1/status_test.go
  config/crd/bases/operator.kyma-project.io_eventings.yaml
  docs/user/02-configuration.md
  internal/controller/operator/eventing/integrationtests/controller/integration_test.go
  internal/controller/operator/eventing/status.go
  test/utils/integration/integration.go
Labels: area/documentation, lgtm, area/eventing, size/L, cla: yes

#310 retrigger build job.
  cmd/main.go
Labels: size/XS, lgtm, cla: yes

#313 Refactor verify script
  scripts/verify-status.sh
Labels: size/M, lgtm, cla: yes

#317 Document Warning State
  api/operator/v1alpha1/eventing_types.go
  docs/user/02-configuration.md
Labels: area/documentation, lgtm, size/S, area/eventing, cla: yes

#319 Semantic versioning in security scan config
  .github/workflows/create-release.yml
  scripts/check_image.sh
  scripts/check_tag_info.sh
  scripts/release.sh
  scripts/verify-status.sh
  sec-scanners-config.yaml
Labels: kind/feature, lgtm, area/eventing, area/ci, size/L, cla: yes

#323 Checkout code
  .github/workflows/create-release.yml
Labels: kind/feature, lgtm, size/S, area/eventing, area/ci, cla: yes

#324 Release input variable for tag checking
  .github/workflows/create-release.yml
Labels: kind/feature, size/XS, lgtm, area/eventing, area/ci, cla: yes

#327 Initial Wait Time
  .github/workflows/create-release.yml
  scripts/verify-status.sh
Labels: kind/feature, size/XS, lgtm, area/eventing, area/ci, cla: yes

#330 Run github action workflows on release-branches.
  .github/workflows/e2e.yml
  .github/workflows/lint.yml
  .github/workflows/sink.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
Labels: lgtm, area/ci, size/L, cla: yes

#315 docs: Adjust Eventing to new content guidelines
  README.md
  docs/assets/evnt-architecture.svg
  docs/assets/evnt-pubsub.svg
  docs/assets/reconcileLoop.svg
  docs/contributor/development.md
  docs/contributor/governance.md
  docs/contributor/installation.md
  docs/contributor/testing.md
  docs/contributor/troubleshooting.md
  docs/user/01-manager.md
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/evnt-architecture.md
  docs/user/evnt-event-names.md
  docs/user/evnt-eventing-metrics.md
  docs/user/resources/_sidebar.md
  docs/user/resources/evnt-cr-subscription.md
  docs/user/troubleshooting/_sidebar.md
  docs/user/troubleshooting/evnt-01-eventing-troubleshooting.md
  docs/user/troubleshooting/evnt-04-free-jetstream-storage.md
  docs/user/tutorials/_sidebar.md
  docs/user/tutorials/evnt-01-prerequisites.md
  docs/user/tutorials/evnt-02-subs-with-multiple-filters.md
  docs/user/tutorials/evnt-03-type-cleanup.md
  docs/user/tutorials/evnt-04-change-max-in-flight-in-sub.md
  docs/user/tutorials/evnt-05-send-legacy-events.md
Labels: area/documentation, lgtm, size/L, cla: yes

#340 Fix release of manifests
  .github/workflows/create-release.yml
  scripts/render_and_upload_manifests.sh
Labels: size/M, lgtm, area/ci, cla: yes

#341 Cheery-pick: fix release of manifests (#340)
  .github/workflows/create-release.yml
  scripts/render_and_upload_manifests.sh
Labels: size/M, lgtm, area/ci, cla: yes

#342 fix reference to release name
  .github/workflows/create-release.yml
Labels: size/XS, lgtm, area/ci, cla: yes

#343 add missing env vars for IMG and MODULE_REGISTERY
  .github/workflows/create-release.yml
Labels: size/XS, lgtm, area/ci, cla: yes

#344 fix wrong token
  .github/workflows/create-release.yml
  scripts/render_and_upload_manifests.sh
Labels: size/XS, lgtm, area/ci, cla: yes

#347 remove call of make module-build
  scripts/render_and_upload_manifests.sh
Labels: size/XS, lgtm, area/ci, cla: yes

#348 fix spelling of env var name
  .github/workflows/create-release.yml
Labels: size/XS, lgtm, area/ci, cla: yes

#349 Cherry pick fixes to release channel
  .github/workflows/create-release.yml
  scripts/render_and_upload_manifests.sh
Labels: lgtm, size/S, area/ci, cla: yes

#335 Improve EventMesh Tests for Better error comparison
  internal/controller/operator/eventing/eventmesh.go
  internal/controller/operator/eventing/eventmesh_test.go
Labels: lgtm, size/L, cla: yes

#356 Bump GOLANG to 1.21.5 and dependencies
  Dockerfile
  api/operator/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_eventings.yaml
  go.mod
  go.sum
Labels: size/M, lgtm, cla: yes

#367 Bump dependencies in eventing-manager
  go.mod
  go.sum
  pkg/object/apirule.go
  pkg/object/apirule_test.go
  pkg/object/equality_test.go
  testing/matchers.go
  testing/test_helpers.go
Labels: size/M, lgtm, cla: yes

#369 bump the image used in sec-scanners-config
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes
