Repository kyma-project/eventing-manager, pull requests merged in 2023-09, with the labels that each got.

#76 Prevent reconciling on more than one Eventing-CR
  api/v1alpha1/eventing_types.go
  cmd/main.go
  config/crd/external/apirules.gateway.crd.yaml
  config/manager/configmap.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  internal/controller/eventing/controller.go
  internal/controller/eventing/controller_test.go
  internal/controller/eventing/integrationtests/controller/integration_test.go
  internal/controller/eventing/integrationtests/controllersinglecr/integration_test.go
  internal/controller/eventing/integrationtests/validation/integration_test.go
  internal/controller/eventing/unit_test.go
  pkg/env/backend_config.go
  test/matchers/matchers.go
  test/utils/integration/integration.go
Labels: size/XL, lgtm

#78 Support switching of backends
  api/v1alpha1/eventing_types.go
  api/v1alpha1/eventing_types_test.go
  api/v1alpha1/status.go
  api/v1alpha1/status_test.go
  config/crd/bases/operator.kyma-project.io_eventings.yaml
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  internal/controller/eventing/controller.go
  internal/controller/eventing/controller_test.go
  internal/controller/eventing/integrationtests/controller/integration_test.go
  internal/controller/eventing/integrationtests/controller_switching/integration_test.go
  pkg/subscriptionmanager/factory.go
  test/utils/options.go
Labels: size/XL, lgtm

#86 Create E2E Tests Workflow (#85)
  e2e/sink/.vscode/launch.json
Labels: lgtm, size/S

#90 Added E2E tests for legacy events
  Makefile
  config/manager/kustomization.yaml
  hack/e2e/common/eventing/publisher.go
  hack/e2e/common/eventing/testsubscriptioninfo.go
  hack/e2e/common/eventing/utils.go
  hack/e2e/common/fixtures/fixtures.go
  hack/e2e/common/http/http.go
  hack/e2e/common/k8s.go
  hack/e2e/common/testenvironment/test_environment.go
  hack/e2e/env/env.go
  hack/e2e/eventing/cleanup/cleanup_test.go
  hack/e2e/eventing/eventing_test.go
  hack/e2e/scripts/event_delivery_tests.sh
  hack/e2e/setup/setup_test.go
Labels: size/XL, lgtm

#88 E2E Tests Sink
  .github/workflows/sink.yml
  e2e/sink/.vscode/launch.json
  hack/e2e/sink/.dockerignore
  hack/e2e/sink/.gitignore
  hack/e2e/sink/Dockerfile
  hack/e2e/sink/Makefile
  hack/e2e/sink/cmd/main.go
  hack/e2e/sink/go.mod
  hack/e2e/sink/go.sum
  hack/e2e/sink/internal/handler/handler.go
  pkg/k8s/client.go
Labels: lgtm, area/ci, size/L

#91 Add root endpoint to store events
  hack/e2e/sink/internal/handler/handler.go
Labels: size/XS, lgtm

#93 Added tests for Cloud Events and verification of reception of events by the Sink
  Makefile
  hack/e2e/common/eventing/publisher.go
  hack/e2e/common/eventing/sinkclient.go
  hack/e2e/common/eventing/utils.go
  hack/e2e/common/fixtures/fixtures.go
  hack/e2e/common/http/http.go
  hack/e2e/common/testenvironment/test_environment.go
  hack/e2e/env/env.go
  hack/e2e/eventing/cleanup/cleanup_test.go
  hack/e2e/eventing/delivery/delivery_test.go
  hack/e2e/eventing/eventing_test.go
  hack/e2e/eventing/setup/setup_test.go
  hack/e2e/scripts/event_delivery_tests.sh
Labels: size/XL, lgtm

#97 Added documentation for e2e tests
  README.md
  hack/e2e/.env.template
  hack/e2e/README.md
Labels: size/M, lgtm

#96 Refactored e2e tests: setup and cleanup code
  hack/e2e/cleanup/cleanup_test.go
  hack/e2e/common/testenvironment/test_environment.go
  hack/e2e/setup/setup_test.go
Labels: lgtm, size/L

#92 Delete Cluster Scoped Resources
  api/v1alpha1/eventing_types.go
  api/v1alpha1/status.go
  api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/eventing/controller.go
  internal/controller/eventing/integrationtests/controller/integration_test.go
  internal/controller/eventing/status.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/k8s/mocks/client.go
  test/utils/integration/integration.go
Labels: lgtm, size/L

#100 Add missing build tags to e2e tests
  hack/e2e/eventing/delivery/delivery_test.go
  hack/e2e/eventing/setup/setup_test.go
Labels: size/XS, lgtm

#102 Watch Cluster-Scoped Resources
  go.mod
  internal/controller/eventing/controller.go
Labels: size/M, lgtm

#98 Replace nolar/setup-k3d-k3s
  .github/workflows/validate.yml
  Makefile
  hack/ci/Makefile
  hack/get_kyma_file_name.sh
Labels: size/M, lgtm, area/ci

#104 Use EC package w/ EventingWebhookAuth Enabled by default
  README.md
  config/manager/manager.yaml
  go.mod
  go.sum
  pkg/subscriptionmanager/factory.go
Labels: size/M, lgtm

#107 enable dependabot
  .github/dependabot.yml
Labels: lgtm, size/S, area/eventing, area/ci

#108 Fixed webhooks and renamed service-account
  config/manager/manager.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/webhook/kustomization.yaml
  config/webhook/webhook_configs.yaml
Labels: size/M, lgtm

#117 Support updating publisher deployment created by eventing-controller
  api/v1alpha1/zz_generated.deepcopy.go
  pkg/eventing/manager.go
  pkg/eventing/manager_test.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/k8s/mocks/client.go
  test/utils.go
Labels: lgtm, size/L

#87 React to NATS backend config changes
  api/v1alpha1/eventing_types.go
  config/crd/bases/operator.kyma-project.io_eventings.yaml
  go.mod
  internal/controller/eventing/controller.go
  internal/controller/eventing/mocks/controller.go
  internal/controller/eventing/mocks/manager.go
  internal/controller/eventing/mocks/nats_config_handler.go
  internal/controller/eventing/nats.go
  internal/controller/eventing/nats_test.go
  internal/controller/eventing/status.go
  internal/controller/eventing/utils.go
  pkg/eventing/mocks/manager.go
  pkg/k8s/mocks/client.go
  pkg/subscriptionmanager/mocks/ec/manager.go
  pkg/subscriptionmanager/mocks/manager_factory.go
Labels: lgtm, size/L
