Repository kyma-project/eventing-manager, pull requests merged in 2023-11, with the labels that each got.

#202 Added webhook cert image to security scanner config
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#210 Add the domain config to the readme
  README.md
Labels: lgtm, size/S, area/eventing

#209 include namespace in delivery metrics
  pkg/backend/jetstream/jetstream.go
  pkg/backend/metrics/collector.go
Labels: size/M, lgtm, area/eventing

#205 Create PeerAuthentications on eventing-manager start if Istio is enabled
  .github/workflows/e2e.yml
  Makefile
  cmd/main.go
  config/crd/for-tests/applications.applicationconnector.crd.yaml
  config/crd/for-tests/security.istio.io_peerauthentication.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  hack/ci/Makefile
  hack/e2e/cleanup/cleanup_test.go
  hack/e2e/common/fixtures/fixtures.go
  hack/e2e/common/k8s.go
  hack/e2e/common/testenvironment/test_environment.go
  hack/e2e/eventing/cleanup/cleanup_test.go
  hack/e2e/eventing/peerauthentications/peerauthentications_test.go
  internal/controller/eventing/controller.go
  pkg/eventing/manager.go
  pkg/istio/peerauthentication/peerauthentication.go
  pkg/istio/peerauthentication/peerauthentication_test.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/k8s/mocks/client.go
  pkg/k8s/types.go
  test/utils/utils.go
Labels: lgtm, area/ci, size/XXL

#212 Bump images and version for Release 1.0.0
  .version
  config/manager/manager.yaml
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#215 Add rc-tag to security scanners
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#221 Updated readme and makefile
  .github/workflows/test.yml
  Makefile
  README.md
  docs/user/troubleshooting/evnt-01-eventing-troubleshooting.md
Labels: area/documentation, lgtm, area/ci, size/L

#224 Remove parallel test run
  internal/controller/eventing/integrationtests/controller/integration_test.go
Labels: size/M, lgtm

#226 Eventing Manager Module Documentation
  Makefile
  docs/assets/reconcileLoop.svg
  docs/contributor/development.md
  docs/contributor/governance.md
  docs/contributor/installation.md
  docs/contributor/testing.md
  docs/contributor/troubleshooting.md
  docs/user/01-manager.md
  docs/user/02-configuration.md
  docs/user/README.md
Labels: area/documentation, lgtm, size/L

#233 Closing NATS connection on subscription manager shutdown and disable parallel reconciliations
  api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/eventing/controller.go
  internal/controller/eventing/mocks/controller.go
  internal/controller/eventing/mocks/manager.go
  internal/controller/eventing/mocks/nats_config_handler.go
  internal/controller/eventing/nats.go
  pkg/backend/jetstream/jetstream.go
  pkg/backend/jetstream/mocks/Backend.go
  pkg/backend/jetstream/mocks/JetStreamContext.go
  pkg/backend/jetstream/types.go
  pkg/ems/api/events/client/mocks/PublisherManager.go
  pkg/eventing/mocks/manager.go
  pkg/k8s/mocks/client.go
  pkg/subscriptionmanager/jetstream/jetstream.go
  pkg/subscriptionmanager/manager/mocks/manager.go
  pkg/subscriptionmanager/mocks/manager_factory.go
  pkg/watcher/mocks/watcher.go
Labels: area/documentation, size/M, lgtm

#234 Update the sec-scanner-config.yaml to the latest build.
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#217 add additional label consumer name on dispatching metrics
  pkg/backend/jetstream/jetstream.go
  pkg/backend/metrics/collector.go
Labels: lgtm, size/S

#238 Remove ClusterRole for subscription with incorrect group
  config/rbac/role.yaml
  internal/controller/eventing/controller.go
  pkg/eventing/utils.go
  test/utils/utils.go
Labels: size/M, lgtm

#242 Bump dependencies.
  Dockerfile
  api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
Labels: size/M, lgtm

#244 Fix navigation files
  docs/user/troubleshooting/_sidebar.md
  docs/user/tutorials/_sidebar.md
Labels: area/documentation, lgtm, size/S

#245 Prepare release 1.0.1
  .version
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#246 Add the navigation file to the resources folder
  docs/user/resources/_sidebar.md
Labels: size/XS, area/documentation, lgtm

#248 Fix nats stream replica update
  internal/controller/eventing/nats.go
  internal/controller/eventing/nats_test.go
Labels: size/M, lgtm

#243 Increase object pkg test coverage
  pkg/eventing/manager.go
  pkg/object/apirule.go
  pkg/object/apirule_test.go
  pkg/object/equality.go
  pkg/object/equality_test.go
  pkg/object/object.go
Labels: lgtm, area/eventing, size/XXL

#257 Enable Multi-group API support Kubebuilder
  PROJECT
  api/operator.kyma-project.io/v1alpha1/eventing_types.go
  api/operator.kyma-project.io/v1alpha1/eventing_types_test.go
  api/operator.kyma-project.io/v1alpha1/groupversion_info.go
  api/operator.kyma-project.io/v1alpha1/status.go
  api/operator.kyma-project.io/v1alpha1/status_test.go
  api/operator.kyma-project.io/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  hack/e2e/cleanup/cleanup_test.go
  hack/e2e/common/fixtures/fixtures.go
  hack/e2e/common/k8s.go
  hack/e2e/common/testenvironment/test_environment.go
  hack/e2e/env/env.go
  hack/e2e/setup/setup_test.go
  internal/controller/operator.kyma-project.io/eventing/controller.go
  internal/controller/operator.kyma-project.io/eventing/controller_test.go
  internal/controller/operator.kyma-project.io/eventing/domain.go
  internal/controller/operator.kyma-project.io/eventing/domain_test.go
  internal/controller/operator.kyma-project.io/eventing/eventmesh.go
  internal/controller/operator.kyma-project.io/eventing/eventmesh_test.go
  internal/controller/operator.kyma-project.io/eventing/integrationtests/controller/integration_test.go
  internal/controller/operator.kyma-project.io/eventing/integrationtests/controller_switching/integration_test.go
  internal/controller/operator.kyma-project.io/eventing/integrationtests/controllersinglecr/integration_test.go
  internal/controller/operator.kyma-project.io/eventing/integrationtests/nats_disabled/integration_test.go
  internal/controller/operator.kyma-project.io/eventing/integrationtests/validation/integration_test.go
  internal/controller/operator.kyma-project.io/eventing/integrationtests/without_apirule_crd/integration_test.go
  internal/controller/operator.kyma-project.io/eventing/mocks/controller.go
  internal/controller/operator.kyma-project.io/eventing/mocks/manager.go
  internal/controller/operator.kyma-project.io/eventing/mocks/nats_config_handler.go
  internal/controller/operator.kyma-project.io/eventing/nats.go
  internal/controller/operator.kyma-project.io/eventing/nats_test.go
  internal/controller/operator.kyma-project.io/eventing/service_instance_secret.go
  internal/controller/operator.kyma-project.io/eventing/status.go
  internal/controller/operator.kyma-project.io/eventing/unit_test.go
  internal/controller/operator.kyma-project.io/eventing/utils.go
  internal/controller/operator.kyma-project.io/eventing/utils_test.go
  internal/controller/operator.kyma-project.io/eventing/webhook.go
  internal/controller/operator.kyma-project.io/eventing/webhook_test.go
  pkg/backend/jetstream/mocks/Backend.go
  pkg/backend/jetstream/mocks/JetStreamContext.go
  pkg/ems/api/events/client/mocks/PublisherManager.go
  pkg/env/nats_config.go
  pkg/eventing/deployment.go
  pkg/eventing/deployment_test.go
  pkg/eventing/manager.go
  pkg/eventing/manager_test.go
  pkg/eventing/mocks/manager.go
  pkg/eventing/utils.go
  pkg/eventing/utils_test.go
  pkg/k8s/mocks/client.go
  pkg/subscriptionmanager/factory.go
  pkg/subscriptionmanager/manager/mocks/manager.go
  pkg/subscriptionmanager/mocks/manager_factory.go
  pkg/watcher/mocks/watcher.go
  test/matchers/matchers.go
  test/utils/integration/integration.go
  test/utils/options.go
  test/utils/utils.go
Labels: lgtm, size/L

#264 Use common labels
  Dockerfile
  config/default/kustomization.yaml
  config/ui-extensions/eventing/kustomization.yaml
  config/ui-extensions/subscriptions/subscriptions.yaml
  internal/controller/operator.kyma-project.io/eventing/controller.go
  internal/controller/operator.kyma-project.io/eventing/eventmesh.go
  internal/controller/operator.kyma-project.io/eventing/eventmesh_test.go
  internal/label/label.go
  pkg/eventing/deployment.go
  pkg/eventing/deployment_test.go
  pkg/eventing/manager.go
  pkg/eventing/utils.go
  pkg/eventing/utils_test.go
  pkg/object/equality_test.go
Labels: lgtm, area/eventing, size/L

#269 Make Eventing CR read if NATS CR in warning state
  go.mod
  go.sum
  pkg/eventing/manager.go
  pkg/eventing/manager_test.go
Labels: kind/bug, size/M, lgtm, area/eventing

#273 Cache runtime objects only created by the EventingManager
  cmd/main.go
  internal/controller/cache/cache.go
  internal/controller/cache/cache_test.go
  internal/controller/client/client.go
  internal/controller/client/client_test.go
  internal/label/label.go
  internal/label/label_test.go
Labels: kind/bug, area/documentation, lgtm, area/eventing, size/L, cla: yes
