Repository kyma-project/eventing-manager, pull requests merged in 2023-10, with the labels that each got.

#121 Added Subscription Busola UI, eventing default CRs and health+metrics service
  config/busola/busola-extension.yaml
  config/busola/kustomization.yaml
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/manager/service.yaml
  config/samples/default.yaml
  config/samples/default_eventmesh.yaml
  config/samples/eventing_short.yaml
  config/samples/kustomization.yaml
Labels: lgtm, size/L

#126 Add ApplicationCRD Enabled ENV in Publisher deployment
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/kustomization.yaml
  config/manager/manager.yaml
  go.mod
  internal/controller/eventing/controller.go
  internal/controller/eventing/integrationtests/controller/integration_test.go
  internal/controller/eventing/mocks/controller.go
  internal/controller/eventing/mocks/manager.go
  internal/controller/eventing/mocks/nats_config_handler.go
  internal/controller/eventing/nats.go
  internal/controller/eventing/unit_test.go
  internal/controller/eventing/utils.go
  pkg/env/backend_config.go
  pkg/eventing/deployment.go
  pkg/eventing/deployment_test.go
  pkg/eventing/manager.go
  pkg/eventing/mocks/manager.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/k8s/mocks/client.go
  pkg/k8s/types.go
  pkg/subscriptionmanager/mocks/ec/manager.go
  pkg/subscriptionmanager/mocks/manager_factory.go
  test/utils/integration/integration.go
  test/utils/utils.go
Labels: lgtm, size/L

#127 Add tasks for module build in Makefile
  .gitignore
  .version
  Makefile
  hack/ci/Makefile
  module-config-template.yaml
  scripts/release.sh
  sec-scanners-config.yaml
Labels: lgtm, size/L

#132 create ghithub action to run the end-to-end tests without lifecycle manager with nats as a backend
  .github/workflows/e2e.yml
  cmd/main.go
  hack/ci/Makefile
  hack/ci/check-k8s-resource-is-ready.sh
  hack/e2e/common/testenvironment/test_environment.go
  hack/e2e/setup/setup_test.go
Labels: lgtm, area/eventing, area/ci, size/L

#133 Migrate JetStream code from eventing-controller
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/operator.kyma-project.io_eventings.yaml
  go.mod
  go.sum
  internal/controller/eventing/controller.go
  internal/controller/eventing/controller_test.go
  internal/controller/eventing/eventmesh_test.go
  internal/controller/eventing/mocks/manager.go
  internal/controller/eventing/nats.go
  internal/controller/eventing/nats_test.go
  internal/controller/eventing/unit_test.go
  internal/controller/subscription/jetstream/errors.go
  internal/controller/subscription/jetstream/matchers_test.go
  internal/controller/subscription/jetstream/reconciler.go
  internal/controller/subscription/jetstream/reconciler_integration_test.go
  internal/controller/subscription/jetstream/reconciler_internal_unit_test.go
  internal/controller/subscription/jetstream/test_utils_test.go
  internal/controller/subscription/jetstream/utils.go
  internal/controller/subscription/jetstream/utils_unit_test.go
  pkg/backend/jetstream/config.go
  pkg/backend/jetstream/config_internal_unit_test.go
  pkg/backend/jetstream/connection.go
  pkg/backend/jetstream/connection_integration_test.go
  pkg/backend/jetstream/errors.go
  pkg/backend/jetstream/jetstream.go
  pkg/backend/jetstream/jetstream_integration_test.go
  pkg/backend/jetstream/jetstream_internal_unit_test.go
  pkg/backend/jetstream/mocks/Backend.go
  pkg/backend/jetstream/mocks/JetStreamContext.go
  pkg/backend/jetstream/stubs_test.go
  pkg/backend/jetstream/test_helpers.go
  pkg/backend/jetstream/types.go
  pkg/backend/jetstream/utils.go
  pkg/backend/jetstream/utils_internal_integration_test.go
  pkg/backend/jetstream/utils_internal_unit_test.go
  pkg/eventing/manager_test.go
  pkg/eventing/mocks/interfaces.go
  pkg/subscriptionmanager/factory.go
  pkg/subscriptionmanager/jetstream/jetstream.go
  pkg/subscriptionmanager/jetstream/jetstream_test.go
  pkg/subscriptionmanager/manager/manager.go
  pkg/subscriptionmanager/manager/mocks/manager.go
  pkg/subscriptionmanager/mocks/manager_factory.go
  test/utils/integration/integration.go
Labels: lgtm, size/XXL

#136 Migrate codebase from EC to eventing-manager - Part 3
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  internal/controller/errors/skip.go
  internal/controller/errors/skip_unit_test.go
  internal/controller/eventing/controller.go
  internal/controller/eventing/controller_test.go
  internal/controller/eventing/eventmesh.go
  internal/controller/eventing/eventmesh_test.go
  internal/controller/eventing/unit_test.go
  internal/controller/events/events.go
  internal/controller/subscription/eventmesh/reconciler.go
  internal/controller/subscription/eventmesh/reconciler_internal_integration_test.go
  internal/controller/subscription/eventmesh/test/assertions.go
  internal/controller/subscription/eventmesh/test/reconciler_integration_test.go
  internal/controller/subscription/eventmesh/test/utils.go
  internal/controller/subscription/eventmesh/testwebhookauth/assertions.go
  internal/controller/subscription/eventmesh/testwebhookauth/reconciler_integration_test.go
  internal/controller/subscription/eventmesh/testwebhookauth/utils.go
  internal/controller/subscription/eventmesh/testwithory/assertions.go
  internal/controller/subscription/eventmesh/testwithory/reconciler_integration_test.go
  internal/controller/subscription/eventmesh/testwithory/utils.go
  internal/controller/subscription/eventmesh/utils.go
  internal/controller/subscription/eventmesh/utils_test.go
  internal/controller/subscription/jetstream/reconciler.go
  internal/controller/subscription/jetstream/reconciler_internal_unit_test.go
  internal/controller/subscription/jetstream/test_utils_test.go
  pkg/backend/cleaner/eventmesh.go
  pkg/backend/cleaner/eventmesh_unit_test.go
  pkg/backend/cleaner/jetstream.go
  pkg/backend/cleaner/jetstream_unit_test.go
  pkg/backend/cleaner/types.go
  pkg/backend/eventmesh/eventmesh.go
  pkg/backend/eventmesh/eventmesh_integration_test.go
  pkg/backend/eventtype/clean.go
  pkg/backend/eventtype/clean_internal_unit_test.go
  pkg/backend/eventtype/simple_clean.go
  pkg/backend/eventtype/simple_clean_internal_unit_test.go
  pkg/backend/jetstream/jetstream.go
  pkg/backend/jetstream/jetstream_integration_test.go
  pkg/backend/jetstream/jetstream_internal_unit_test.go
  pkg/backend/jetstream/test_helpers.go
  pkg/backend/jetstream/types.go
  pkg/backend/jetstream/utils_internal_unit_test.go
  pkg/backend/sink/validator.go
  pkg/env/backend_config.go
  pkg/env/backend_config_test.go
  pkg/eventing/deployment.go
  pkg/eventing/manager.go
  pkg/logger/logger.go
  pkg/logger/logger_test.go
  pkg/subscriptionmanager/eventmesh/eventmesh.go
  pkg/subscriptionmanager/eventmesh/eventmesh_test.go
  pkg/subscriptionmanager/factory.go
  pkg/subscriptionmanager/jetstream/jetstream.go
  pkg/subscriptionmanager/jetstream/jetstream_test.go
  pkg/subscriptionmanager/mocks/manager_factory.go
  test/utils.go
  test/utils/integration/integration.go
  testing/test_helpers.go
Labels: lgtm, size/XXL

#123 React to EventMesh backend config changes
  api/v1alpha1/eventing_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/external/apirules.gateway.crd.yaml
  go.mod
  internal/controller/eventing/eventmesh.go
  internal/controller/eventing/eventmesh_test.go
  internal/controller/eventing/integrationtests/controller_switching/integration_test.go
  internal/controller/eventing/mocks/controller.go
  internal/controller/eventing/mocks/manager.go
  internal/controller/eventing/mocks/nats_config_handler.go
  internal/controller/eventing/nats.go
  internal/controller/eventing/nats_test.go
  internal/controller/eventing/status.go
  internal/controller/eventing/utils.go
  pkg/backend/jetstream/mocks/Backend.go
  pkg/backend/jetstream/mocks/JetStreamContext.go
  pkg/ems/api/events/client/mocks/PublisherManager.go
  pkg/eventing/mocks/manager.go
  pkg/k8s/mocks/client.go
  pkg/subscriptionmanager/manager/mocks/manager.go
  pkg/subscriptionmanager/mocks/ec/manager.go
  pkg/subscriptionmanager/mocks/manager_factory.go
Labels: lgtm, size/L

#146 replace intstr.FromInt with instr.FromInt32
  pkg/eventing/deployment.go
Labels: lgtm, size/S, area/eventing

#145 Add PriorityClass
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manager/priority-class.yaml
  config/webhook/cronjob.yaml
  config/webhook/job.yaml
  hack/e2e/common/testenvironment/test_environment.go
  hack/e2e/setup/setup_test.go
  pkg/eventing/deployment.go
  pkg/eventing/deployment_test.go
Labels: lgtm, size/L

#147 streamline how github action workflows get triggered
  .github/workflows/e2e.yml
  .github/workflows/lint.yml
  .github/workflows/sink.yml
  .github/workflows/test.yml
  .github/workflows/validate.yml
Labels: size/M, lgtm, area/ci

#158 Create Release Pipeline
  .github/workflows/create-release.yml
  scripts/check_image.sh
  scripts/check_release_tag.sh
  scripts/create_changelog.sh
  scripts/create_draft_release.sh
  scripts/publish_release.sh
  scripts/release.sh
  scripts/verify_status.sh
Labels: lgtm, area/ci, size/L

#159 remove double import
  test/utils/integration/integration.go
Labels: lgtm, size/S

#143 Watch NATS CR Dynamically
  .github/workflows/lint.yml
  .github/workflows/test.yml
  api/v1alpha1/eventing_types.go
  cmd/main.go
  config/crd/bases/operator.kyma-project.io_eventings.yaml
  go.mod
  go.sum
  internal/controller/eventing/controller.go
  internal/controller/eventing/controller_test.go
  internal/controller/eventing/integrationtests/controller/integration_test.go
  internal/controller/eventing/integrationtests/controller_switching/integration_test.go
  internal/controller/eventing/unit_test.go
  pkg/eventing/mocks/interfaces.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/watcher/mocks/controller.go
  pkg/watcher/mocks/watcher.go
  pkg/watcher/watcher.go
  test/matchers/matchers.go
  test/utils/integration/integration.go
Labels: lgtm, area/ci, size/XXL

#161 Add the latest version security scanners config
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#165 Update image version for release
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#172 Test release manifest creation
  .version
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#152 Read the cluster domain from the Eventing CR or from the ConfigMap
  api/v1alpha1/eventing_types.go
  config/crd/bases/operator.kyma-project.io_eventings.yaml
  config/manager/manager.yaml
  internal/controller/eventing/domain.go
  internal/controller/eventing/domain_test.go
  internal/controller/eventing/eventmesh.go
  internal/controller/eventing/eventmesh_test.go
  internal/controller/eventing/integrationtests/controller/integration_test.go
  internal/controller/eventing/integrationtests/controller_switching/integration_test.go
  internal/controller/eventing/integrationtests/validation/integration_test.go
  internal/controller/eventing/utils.go
  internal/controller/eventing/utils_test.go
  internal/controller/subscription/eventmesh/reconciler.go
  internal/controller/subscription/eventmesh/reconciler_internal_integration_test.go
  internal/controller/subscription/eventmesh/test/utils.go
  internal/controller/subscription/eventmesh/testwebhookauth/utils.go
  internal/controller/subscription/eventmesh/testwithory/utils.go
  pkg/backend/eventmesh/eventmesh_integration_test.go
  pkg/env/config.go
  pkg/env/config_test.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/k8s/mocks/client.go
  pkg/subscriptionmanager/eventmesh/eventmesh.go
  pkg/subscriptionmanager/eventmesh/eventmesh_test.go
  pkg/subscriptionmanager/factory.go
  pkg/subscriptionmanager/mocks/manager_factory.go
  pkg/utils/utils.go
  pkg/utils/utils_unit_test.go
  test/utils/integration/integration.go
  test/utils/options.go
  test/utils/utils.go
Labels: kind/bug, size/XL, lgtm, area/eventing

#173 Bump dependencies
  cmd/main.go
  go.mod
  go.sum
  hack/e2e/common/testenvironment/test_environment.go
  internal/controller/subscription/eventmesh/test/utils.go
  internal/controller/subscription/eventmesh/testwebhookauth/utils.go
  internal/controller/subscription/eventmesh/testwithory/utils.go
  internal/controller/subscription/jetstream/test_utils_test.go
  pkg/eventing/manager_test.go
  pkg/k8s/client.go
  pkg/object/equality_test.go
  test/utils/integration/integration.go
Labels: lgtm, size/L

#176 Bump the golang image in the Dockerfile
  Dockerfile
Labels: size/XS, lgtm

#180 Increase memory limits
  config/manager/manager.yaml
Labels: size/XS, lgtm, area/eventing

#178 Update sec-scanners-config to latest build.
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#182 Increase timeout to 90 seconds in integration test.
  test/utils/integration/integration.go
Labels: size/XS, lgtm

#166 Create UI for Eventing Module
  config/busola/kustomization.yaml
  config/default/kustomization.yaml
  config/ui-extensions/eventing/details
  config/ui-extensions/eventing/form
  config/ui-extensions/eventing/general
  config/ui-extensions/eventing/kustomization.yaml
  config/ui-extensions/eventing/list
  config/ui-extensions/kustomization.yaml
  config/ui-extensions/subscriptions/subscriptions.yaml
Labels: lgtm, size/L

#186 Update to latest image for release 0.1.0
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#188 Cleanup including and excluding paths in github action
  .github/workflows/sink.yml
  .github/workflows/validate.yml
Labels: lgtm, size/S, area/ci

#190 Bump EPP image to latest from main
  config/manager/manager.yaml
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#191 Update version and image for eventing-manager release 0.1.1
  .version
  sec-scanners-config.yaml
Labels: size/XS, lgtm

#194 Check if APIRule CRD is installed, otherwise stop reconciliation for EventMesh
  Makefile
  cmd/main.go
  config/crd/for-tests/apirules.gateway.crd.yaml
  config/crd/for-tests/applications.applicationconnector.crd.yaml
  config/crd/for-tests/operator.kyma-project.io_nats.yaml
  internal/controller/eventing/controller.go
  internal/controller/eventing/controller_test.go
  internal/controller/eventing/integrationtests/controller/integration_test.go
  internal/controller/eventing/integrationtests/controller_switching/integration_test.go
  internal/controller/eventing/integrationtests/controllersinglecr/integration_test.go
  internal/controller/eventing/integrationtests/validation/integration_test.go
  internal/controller/eventing/integrationtests/without_apirule_crd/integration_test.go
  internal/controller/eventing/mocks/controller.go
  internal/controller/eventing/mocks/manager.go
  internal/controller/eventing/mocks/nats_config_handler.go
  internal/controller/subscription/eventmesh/test/utils.go
  internal/controller/subscription/eventmesh/testwebhookauth/utils.go
  internal/controller/subscription/eventmesh/testwithory/utils.go
  pkg/backend/jetstream/mocks/Backend.go
  pkg/backend/jetstream/mocks/JetStreamContext.go
  pkg/ems/api/events/client/mocks/PublisherManager.go
  pkg/eventing/mocks/manager.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/k8s/mocks/client.go
  pkg/k8s/types.go
  pkg/subscriptionmanager/manager/mocks/manager.go
  pkg/subscriptionmanager/mocks/manager_factory.go
  pkg/watcher/mocks/watcher.go
  test/utils/integration/integration.go
  test/utils/utils.go
Labels: lgtm, size/L

#201 Use mockery pkg instead of mockery CLI
  go.mod
  go.sum
  hack/tools.go
  internal/controller/eventing/controller.go
  internal/controller/eventing/mocks/controller.go
  internal/controller/eventing/mocks/manager.go
  internal/controller/eventing/mocks/nats_config_handler.go
  internal/controller/eventing/nats.go
  pkg/backend/jetstream/mocks/Backend.go
  pkg/backend/jetstream/mocks/JetStreamContext.go
  pkg/backend/jetstream/types.go
  pkg/ems/api/events/client/client.go
  pkg/ems/api/events/client/mocks/PublisherManager.go
  pkg/eventing/manager.go
  pkg/eventing/mocks/manager.go
  pkg/k8s/client.go
  pkg/k8s/mocks/client.go
  pkg/subscriptionmanager/factory.go
  pkg/subscriptionmanager/manager/manager.go
  pkg/subscriptionmanager/manager/mocks/manager.go
  pkg/subscriptionmanager/mocks/manager_factory.go
  pkg/watcher/mocks/watcher.go
  pkg/watcher/watcher.go
Labels: size/XL, lgtm

#197 Update default resources in Eventing CR
  api/v1alpha1/eventing_types.go
  config/crd/bases/operator.kyma-project.io_eventings.yaml
  internal/controller/eventing/integrationtests/validation/integration_test.go
Labels: lgtm, size/S

#207 Add github action for links checker for markdown files
  .github/workflows/lint-markdown-links-pr.yml
  .mlc.config.json
Labels: size/M, lgtm, area/ci

#198 docs: Optimize module docs for website
  README.md
  docs/README.md
  docs/assets/evnt-architecture.svg
  docs/assets/evnt-implementation.svg
  docs/assets/evnt-pubsub.svg
  docs/user/README.md
  docs/user/_sidebar.md
  docs/user/evnt-architecture.md
  docs/user/evnt-event-names.md
  docs/user/evnt-eventing-metrics.md
  docs/user/resources/evnt-cr-subscription.md
  docs/user/troubleshooting/README.md
  docs/user/troubleshooting/_sidebar.md
  docs/user/troubleshooting/evnt-01-eventing-troubleshooting.md
  docs/user/troubleshooting/evnt-02-jetstream-troubleshooting.md
  docs/user/troubleshooting/evnt-03-type-collision.md
  docs/user/troubleshooting/evnt-04-free-jetstream-storage.md
  docs/user/troubleshooting/evnt-05-fix-pending-messages.md
  docs/user/troubleshooting/metadata.yaml
  docs/user/tutorials/_sidebar.md
  docs/user/tutorials/evnt-01-prerequisites.md
  docs/user/tutorials/evnt-02-subs-with-multiple-filters.md
  docs/user/tutorials/evnt-03-type-cleanup.md
  docs/user/tutorials/evnt-04-change-max-in-flight-in-sub.md
  docs/user/tutorials/evnt-05-send-legacy-events.md
  docs/user/tutorials/metadata.yaml
Labels: area/documentation, lgtm, size/XXL
