Repository kyma-project/eventing-manager, pull requests merged in 2023-08, with the labels that each got.

#29 Refactored EPP resources creation and added tests
  config/manager/kustomization.yaml
  internal/controller/eventing/controller.go
  internal/controller/eventing/integrationtests/controller/integration_test.go
  pkg/eventing/manager.go
  pkg/eventing/manager_test.go
  pkg/eventing/mocks/manager.go
  pkg/eventing/utils.go
  pkg/eventing/utils_test.go
  test/utils/integration/integration.go
  test/utils/utils.go
Labels: size/XL, lgtm

#35 Prevent HPA and Deployment Replica Fight
  pkg/eventing/deployment.go
Labels: size/XS, lgtm

#44 Added Finalizer to Eventing CR
  go.mod
  internal/controller/eventing/controller.go
  internal/controller/eventing/integrationtests/controller/integration_test.go
  internal/controller/eventing/mocks/controller.go
  internal/controller/eventing/mocks/manager.go
  internal/controller/eventing/unit_test.go
  internal/controller/eventing/utils.go
  internal/controller/eventing/utils_test.go
  test/matchers/matchers.go
  test/utils/options.go
Labels: lgtm, size/XXL

#36 Adding NATS sub manager
  Makefile
  cmd/main.go
  config/manager/kustomization.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/eventing/controller.go
  internal/controller/eventing/nats.go
  internal/controller/eventing/nats_test.go
  internal/controller/eventing/unit_test.go
  pkg/env/backend_config.go
  pkg/env/backend_config_test.go
  pkg/env/nats_config.go
  pkg/env/nats_config_test.go
  pkg/eventing/manager.go
  pkg/eventing/mocks/manager.go
  pkg/subscriptionmanager/factory.go
  pkg/subscriptionmanager/mocks/ec/manager.go
  pkg/subscriptionmanager/mocks/manager_factory.go
  test/utils/integration/integration.go
Labels: lgtm, size/XXL

#49 Fixed flaky unit tests
  internal/controller/eventing/controller.go
  test/utils/integration/integration.go
Labels: size/XS, lgtm, area/ci

#50 Added unit test
  api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/eventing/integrationtests/controller/integration_test.go
  internal/controller/eventing/nats_test.go
  test/utils/integration/integration.go
Labels: size/M, lgtm

#58 Update README.md
  README.md
Labels: size/XS, lgtm

#61 Renamed EPP to Publisher
  api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/eventing/controller.go
  internal/controller/eventing/integrationtests/controller/integration_test.go
  internal/controller/eventing/unit_test.go
  pkg/eventing/deployment.go
  pkg/eventing/manager.go
  pkg/eventing/manager_test.go
  pkg/eventing/utils.go
  pkg/eventing/utils_test.go
  test/utils/integration/integration.go
Labels: lgtm, size/L

#62 Use latest EPP image for Kustomize resources
  config/manager/manager.yaml
Labels: size/XS, lgtm

#59 change reuse contact information
  .reuse/dep5
Labels: size/XS, lgtm

#68 Added webhook cert job and refactored kustomize configs
  Makefile
  config/crd/external/applications.applicationconnector.crd.yaml
  config/crd/external/subscriptions.eventing.kyma-project.io.crd.yaml
  config/crd/kustomization.yaml
  config/crd/patches/webhook_in_subscriptions.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/configmap.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/rbac/webhook_role.yaml
  config/rbac/webhook_role_binding.yaml
  config/rbac/webhook_service_account.yaml
  config/webhook/cronjob.yaml
  config/webhook/job.yaml
  config/webhook/kustomization.yaml
  config/webhook/service.yaml
  config/webhook/webhook_configs.yaml
  internal/controller/eventing/controller.go
Labels: lgtm, size/XXL

#60 Reconcile CABundle in webhook configurations
  Makefile
  api/v1alpha1/eventing_types.go
  api/v1alpha1/status.go
  cmd/main.go
  config/manager/kustomization.yaml
  internal/controller/eventing/controller.go
  internal/controller/eventing/eventmesh.go
  internal/controller/eventing/integrationtests/controller/integration_test.go
  internal/controller/eventing/status.go
  internal/controller/eventing/unit_test.go
  internal/controller/eventing/webhook.go
  internal/controller/eventing/webhook_test.go
  pkg/env/backend_config.go
  pkg/eventing/manager.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/k8s/mocks/client.go
  test/utils/integration/integration.go
Labels: size/XL, lgtm

#70 Update Eventing spec to use only one backend
  api/v1alpha1/eventing_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.kyma-project.io_eventings.yaml
  config/manager/kustomization.yaml
  config/samples/operator_v1alpha1_eventing.yaml
  config/samples/operator_v1alpha1_eventing_eventmesh.yaml
  config/samples/operator_v1alpha1_eventing_short.yaml
  internal/controller/eventing/controller.go
  internal/controller/eventing/eventmesh.go
  internal/controller/eventing/integrationtests/validation/integration_test.go
  internal/controller/eventing/nats.go
  pkg/env/nats_config.go
  pkg/env/nats_config_test.go
  pkg/eventing/deployment.go
  test/matchers/matchers.go
  test/utils/integration/integration.go
  test/utils/options.go
  test/utils/utils.go
Labels: size/XL, lgtm, area/eventing

#72 Implement Starting EventMesh Subscription Manager
  Makefile
  api/v1alpha1/eventing_types.go
  api/v1alpha1/status.go
  cmd/main.go
  config/default/configmap_patch.yaml
  config/default/kustomization.yaml
  config/manager/configmap.yaml
  go.mod
  internal/controller/eventing/controller.go
  internal/controller/eventing/eventmesh.go
  internal/controller/eventing/eventmesh_test.go
  internal/controller/eventing/integrationtests/controller/integration_test.go
  internal/controller/eventing/status.go
  pkg/subscriptionmanager/factory.go
  pkg/subscriptionmanager/mocks/manager_factory.go
  test/matchers/matchers.go
  test/utils/integration/integration.go
  test/utils/options.go
  test/utils/utils.go
Labels: lgtm, size/XXL
