Repository kyma-project/eventing-manager, pull requests merged in 2023-06, with the labels that each got.

#10 Added lint check pre-main job and updated codeowners
  .github/workflows/lint.yml
  CODEOWNERS
Labels: size/M, lgtm, area/eventing, area/ci

#6 Scaffold a new controller using kubebuilder
  .dockerignore
  .gitignore
  Dockerfile
  Makefile
  PROJECT
  README.md
  api/v1alpha1/eventing_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/operator.kyma-project.io_eventings.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_eventings.yaml
  config/crd/patches/webhook_in_eventings.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/eventing_editor_role.yaml
  config/rbac/eventing_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/samples/kustomization.yaml
  config/samples/operator_v1alpha1_eventing.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  internal/controller/eventing/controller.go
  internal/controller/suite_test.go
Labels: lgtm, area/eventing, area/ci, size/XXL

#14 Update CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm

#15 add a gh action to validate the crd
  .github/workflows/validatecrd.yml
Labels: lgtm, size/S, area/ci
