Repository kyma-project/eventing-manager, pull requests merged in 2023-07, with the labels that each got.

#21 Add validation and defaults for eventing CR
  .mockery.yaml
  Makefile
  api/v1alpha1/eventing_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/operator.kyma-project.io_eventings.yaml
  config/samples/operator_v1alpha1_eventing.yaml
  go.mod
  go.sum
  internal/controller/eventing/integrationtests/validation/integration_test.go
  test/matchers/matchers.go
  test/utils.go
  test/utils/integration/integration.go
Labels: lgtm, size/XXL

#23 Implement Eventing Manager NATS Mode
  .gitignore
  Dockerfile
  Makefile
  README.md
  api/v1alpha1/eventing_types.go
  api/v1alpha1/status.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/operator.kyma-project.io_eventings.yaml
  config/crd/external/operator.kyma-project.io_nats.yaml
  config/default/configmap_patch.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/configmap.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/publisher-proxy/clusterrole.yaml
  config/publisher-proxy/clusterrolebinding.yaml
  config/publisher-proxy/configmap.yaml
  config/publisher-proxy/kustomization.yaml
  config/publisher-proxy/peerauthentication.yaml
  config/publisher-proxy/service.yaml
  config/publisher-proxy/serviceaccount.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/eventing_editor_role.yaml
  config/rbac/eventing_viewer_role.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/samples/kustomization.yaml
  config/samples/operator_v1alpha1_eventing.yaml
  config/samples/operator_v1alpha1_eventing_short.yaml
  go.mod
  go.sum
  internal/controller/eventing/controller.go
  internal/controller/eventing/integrationtests/controller/integration_test.go
  internal/controller/eventing/integrationtests/validation/integration_test.go
  internal/controller/eventing/status.go
  internal/controller/suite_test.go
  pkg/eventing/hpa.go
  pkg/eventing/manager.go
  pkg/eventing/manager_test.go
  pkg/eventing/mocks/interfaces.go
  pkg/eventing/mocks/manager.go
  pkg/k8s/client.go
  pkg/k8s/mocks/client.go
  test/matchers/matchers.go
  test/utils/integration/integration.go
  test/utils/options.go
  test/utils/utils.go
Labels: lgtm, size/XXL

#26 Create/Delete Publisher Proxy k8s resources with Eventing CR
  .gitignore
  cmd/main.go
  config/crd/external/peerauthentications.security.istio.io.yaml
  config/default/kustomization.yaml
  config/manager/kustomization.yaml
  config/publisher-proxy/clusterrole.yaml
  config/publisher-proxy/clusterrolebinding.yaml
  config/publisher-proxy/configmap.yaml
  config/publisher-proxy/kustomization.yaml
  config/publisher-proxy/peerauthentication.yaml
  config/publisher-proxy/service.yaml
  config/publisher-proxy/serviceaccount.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/eventing/controller.go
  internal/controller/eventing/integrationtests/controller/integration_test.go
  internal/controller/eventing/integrationtests/validation/integration_test.go
  pkg/eventing/hpa.go
  pkg/eventing/manager.go
  pkg/eventing/manager_test.go
  pkg/eventing/utils.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/k8s/mocks/client.go
  pkg/k8s/types.go
  test/utils.go
  test/utils/integration/integration.go
  test/utils/utils.go
Labels: lgtm, size/XXL

#28 Removed peer authentication creation
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/external/peerauthentications.security.istio.io.yaml
  config/rbac/role.yaml
  internal/controller/eventing/controller.go
  pkg/eventing/manager.go
  pkg/eventing/utils.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/k8s/mocks/client.go
  pkg/k8s/types.go
  test/utils/integration/integration.go
  test/utils/utils.go
Labels: lgtm, size/L

#30 Copy EC Publisher Proxy Code and Use SSA
  .gitignore
  api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  internal/controller/eventing/controller.go
  internal/controller/eventing/integrationtests/controller/integration_test.go
  pkg/eventing/deployment.go
  pkg/eventing/deployment_test.go
  pkg/eventing/manager.go
  pkg/eventing/manager_test.go
  pkg/eventing/mocks/manager.go
  pkg/eventing/utils.go
  pkg/k8s/client.go
  pkg/k8s/client_test.go
  pkg/k8s/mocks/client.go
  test/matchers/matchers.go
  test/utils/integration/integration.go
  test/utils/utils.go
Labels: lgtm, size/XXL

#31 Use prefix from Eventing CR
  api/v1alpha1/eventing_types.go
  cmd/main.go
  config/crd/bases/operator.kyma-project.io_eventings.yaml
  config/samples/operator_v1alpha1_eventing.yaml
  go.mod
  internal/controller/eventing/integrationtests/controller/integration_test.go
  internal/controller/eventing/integrationtests/validation/integration_test.go
  pkg/env/backend_config.go
  pkg/env/backend_config_test.go
  pkg/env/nats_config.go
  pkg/env/nats_config_test.go
  pkg/eventing/deployment.go
  pkg/eventing/deployment_test.go
  pkg/eventing/manager.go
  pkg/eventing/manager_test.go
  test/matchers/matchers.go
  test/utils.go
  test/utils/integration/integration.go
  test/utils/options.go
Labels: size/XL, lgtm
