Repository kyma-project/eventing-manager, pull requests merged in 2024-02, with the labels that each got.

#455 Correct post-eventing-manager-build name
  .github/workflows/push-e2e-upgrade-test.yaml
Labels: size/XS, lgtm, area/eventing, area/ci, cla: yes

#456 Change Eventing CR status to WARN if cannot connect to NATS
  internal/controller/operator/eventing/controller.go
  internal/controller/operator/eventing/integrationtests/natsconnection/integration_test.go
  test/utils/integration/integration.go
Labels: size/M, lgtm, cla: yes

#459 Use checkout GH action branch setting
  .github/workflows/e2e-upgrade-test-reusable.yaml
  .github/workflows/pull-e2e-upgrade-test.yaml
  .github/workflows/push-e2e-upgrade-test.yaml
Labels: lgtm, size/S, area/ci, cla: yes

#460 Bump rc-tag on main to 1.1.0
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#461 Don't use shell script file in GHA workflow
  .github/workflows/e2e-upgrade-test-reusable.yaml
Labels: lgtm, size/S, area/ci, cla: yes

#475 Bump mockery image to 2.40.3
  api/operator/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  internal/connection/nats/mocks/connection.go
  internal/controller/operator/eventing/mocks/controller.go
  internal/controller/operator/eventing/mocks/manager.go
  internal/controller/operator/eventing/mocks/nats_config_handler.go
  pkg/backend/jetstream/mocks/Backend.go
  pkg/backend/jetstream/mocks/JetStreamContext.go
  pkg/ems/api/events/client/mocks/PublisherManager.go
  pkg/eventing/mocks/manager.go
  pkg/k8s/mocks/client.go
  pkg/subscriptionmanager/manager/mocks/manager.go
  pkg/subscriptionmanager/mocks/manager_factory.go
  pkg/watcher/mocks/watcher.go
Labels: size/M, lgtm, cla: yes

#485 docs: Apply the flexible alerts plugin to Eventing docs
  README.md
  docs/user/resources/evnt-cr-subscription.md
  docs/user/troubleshooting/evnt-04-free-jetstream-storage.md
  docs/user/tutorials/evnt-02-subs-with-multiple-filters.md
  docs/user/tutorials/evnt-03-type-cleanup.md
  docs/user/tutorials/evnt-04-change-max-in-flight-in-sub.md
  docs/user/tutorials/evnt-05-send-legacy-events.md
Labels: documentation, area/documentation, size/M, lgtm, kind/chore, cla: yes

#472 Bump sec-scanners-config and kustomize file in create release workflow
  .github/workflows/create-release.yml
  hack/ci/bump-kustomize-file.sh
  hack/ci/create_changelog.sh
  hack/ci/create_draft_release.sh
  hack/ci/get-version-from-branch.sh
  hack/ci/publish_release.sh
  hack/ci/render-sec-scanners-config.sh
  hack/ci/render_and_upload_manifests.sh
  hack/ci/wait-for-release-build-job.sh
  scripts/check_sec-scanners-config.sh
  scripts/create_changelog.sh
Labels: lgtm, area/ci, size/L, cla: yes

#482 feat: add rules for PRs
  .github/dependabot.yml
  .github/workflows/lint-conventional-prs.yml
Labels: size/M, lgtm, area/ci, cla: yes

#328 Document Eventing States More Detailed
  api/operator/v1alpha1/eventing_types.go
  docs/user/02-configuration.md
Labels: area/documentation, lgtm, size/S, cla: yes

#497 chore: change dependabot config to weekly schedule
  .github/dependabot.yml
Labels: lgtm, size/S, area/ci, cla: yes

#503 Simplify retry function
  hack/e2e/common/retry.go
Labels: size/M, lgtm, cla: yes

#504 docs: Switch preposition, its IN a cluster not ON a cluster
  README.md
  docs/contributor/installation.md
  docs/user/tutorials/evnt-01-prerequisites.md
Labels: area/documentation, lgtm, size/S, cla: yes

#498 Chore: Bump dependencies
  go.mod
  go.sum
Labels: lgtm, size/S, cla: yes

#502 doc: Fix Eventing State doc formatting
  docs/user/02-configuration.md
Labels: area/documentation, size/M, lgtm, cla: yes

#510 chore: bump dependencies
  api/eventing/v1alpha1/zz_generated.deepcopy.go
  api/eventing/v1alpha2/zz_generated.deepcopy.go
  api/operator/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/eventing.kyma-project.io_subscriptions.yaml
  config/crd/bases/operator.kyma-project.io_eventings.yaml
  config/rbac/role.yaml
  config/webhook/manifests.yaml
  go.mod
  go.sum
  internal/connection/nats/mocks/connection.go
  internal/controller/operator/eventing/mocks/controller.go
  internal/controller/operator/eventing/mocks/manager.go
  internal/controller/operator/eventing/mocks/nats_config_handler.go
  pkg/backend/jetstream/mocks/Backend.go
  pkg/backend/jetstream/mocks/JetStreamContext.go
  pkg/ems/api/events/client/mocks/PublisherManager.go
  pkg/eventing/mocks/manager.go
  pkg/k8s/client_test.go
  pkg/k8s/mocks/client.go
  pkg/subscriptionmanager/manager/mocks/manager.go
  pkg/subscriptionmanager/mocks/manager_factory.go
  pkg/watcher/mocks/watcher.go
Labels: lgtm, size/L, cla: yes
