Repository kyma-project/eventing-manager, pull requests merged in 2024-04, with the labels that each got.

#534 fix: create epp secret in epp-deployment ns
  .github/workflows/lint-conventional-prs.yml
  .github/workflows/lint-go.yml
  .golangci.yaml
  api/operator/v1alpha1/eventing_types_test.go
  hack/e2e/common/eventing/utils.go
  hack/e2e/common/k8s.go
  internal/controller/operator/eventing/controller.go
  internal/controller/operator/eventing/controller_test.go
  internal/controller/operator/eventing/eventmesh.go
  internal/controller/operator/eventing/eventmesh_test.go
  internal/controller/operator/eventing/integrationtests/controller/integration_test.go
Labels: lgtm, area/ci, size/L, cla: yes

#550 fix: check title gh-action
  .github/workflows/lint-conventional-prs.yml
Labels: size/XS, lgtm, area/ci, cla: yes

#545 chore: added comments to explain that LastTransistionTime will not update
  api/operator/v1alpha1/status.go
Labels: size/XS, lgtm, cla: yes

#555 chore: update golangci to 1.57
  .github/workflows/create-release.yml
  .github/workflows/lint-go.yml
  .github/workflows/sink.yml
  .golangci.yaml
  Makefile
  api/operator/v1alpha1/status_test.go
  internal/controller/errors/skip.go
  internal/controller/eventing/subscription/jetstream/test_utils_test.go
  internal/controller/operator/eventing/eventmesh_test.go
  internal/controller/operator/eventing/integrationtests/controller/integration_test.go
  internal/controller/operator/eventing/nats_test.go
  pkg/backend/cleaner/eventmesh.go
  pkg/backend/jetstream/config_internal_unit_test.go
  pkg/backend/jetstream/jetstream_integration_test.go
  pkg/utils/utils_unit_test.go
  pkg/watcher/watcher.go
  test/utils/integration/integration.go
  testing/eventmeshmock.go
Labels: lgtm, area/ci, size/L, cla: yes

#556 fix: updated conditions to check for readiness of deployment
  api/operator/v1alpha1/zz_generated.deepcopy.go
  internal/controller/operator/eventing/status.go
  internal/controller/operator/eventing/status_test.go
Labels: lgtm, size/L, cla: yes

#539 fix: the Eventing API docs
  api/operator/v1alpha1/eventing_types.go
  config/crd/bases/operator.kyma-project.io_eventings.yaml
  docs/user/02-configuration.md
Labels: documentation, area/documentation, lgtm, area/eventing, size/L, cla: yes
