Repository kyma-project/eventing-manager, pull requests merged in 2024-05, with the labels that each got.

#569 docs: improve the troubleshooting guide for Eventing
  docs/user/troubleshooting/evnt-05-fix-pending-messages.md
Labels: size/XS, area/documentation, lgtm, cla: yes

#572 chore: deprecate kyma provision gardener
  hack/ci/Makefile
  scripts/gardener/aws/provision.sh
Labels: size/M, lgtm, cla: yes

#574 fix: fix typo in Gardener provisioning
  scripts/gardener/aws/provision.sh
Labels: size/XS, lgtm, cla: yes

#576 fix: change NATS CR wait for Warning status
  .github/workflows/e2e-backend-switching-reuseable.yml
  hack/ci/Makefile
Labels: size/XS, lgtm, area/ci, cla: yes

#578 fix: unify CR description in Kyma dashboard
  config/ui-extensions/eventing/general
Labels: size/XS, lgtm, cla: yes
