Repository kyma-project/eventing-manager, pull requests merged in 2024-01, with the labels that each got.

#355 Retry instead of panicking immediately
  testing/eventmeshmock.go
Labels: lgtm, size/S, cla: yes

#379 Fix e2e job NATS Install step
  .github/workflows/e2e.yml
  hack/ci/Makefile
  testing/eventmeshmock.go
Labels: lgtm, size/S, area/ci, cla: yes

#384 Remove panic from test
  testing/eventmeshmock.go
Labels: size/XS, lgtm, cla: yes

#378 Enable goerr113 linting for EventMesh tests
  internal/controller/operator/eventing/eventmesh_test.go
Labels: lgtm, size/S, area/eventing, cla: yes

#275 Use created-by label to cache runtime objects
  internal/controller/cache/cache.go
  internal/controller/cache/cache_test.go
  internal/label/label.go
  internal/label/label_test.go
Labels: lgtm, size/S, area/eventing, cla: yes

#388 Init for backend switching action
  .github/workflows/e2e-k8s.yml
  .github/workflows/e2e.yml
Labels: size/M, lgtm, area/ci, cla: yes

#391 Fix backend switching initial trigger setup
  .github/workflows/e2e-k8s.yml
Labels: size/XS, lgtm, area/ci, cla: yes

#394 Adapt tabs and add README files for nav
  docs/user/_sidebar.md
  docs/user/resources/README.md
  docs/user/tutorials/evnt-02-subs-with-multiple-filters.md
  docs/user/tutorials/evnt-03-type-cleanup.md
  docs/user/tutorials/evnt-04-change-max-in-flight-in-sub.md
  docs/user/tutorials/evnt-05-send-legacy-events.md
Labels: documentation, area/documentation, size/XL, lgtm, cla: yes

#395 Update tabs config
  docs/user/tutorials/evnt-02-subs-with-multiple-filters.md
  docs/user/tutorials/evnt-03-type-cleanup.md
  docs/user/tutorials/evnt-04-change-max-in-flight-in-sub.md
  docs/user/tutorials/evnt-05-send-legacy-events.md
Labels: area/documentation, size/M, lgtm, cla: yes

#396 Release without version input
  .github/workflows/create-release.yml
  scripts/check_sec-scanners-config.sh
Labels: size/M, lgtm, area/ci, cla: yes

#400 Add backend switching job for EventMesh on Push event
  .github/workflows/e2e-backend-switching-reuseable.yml
  .github/workflows/e2e.yml
  hack/ci/Makefile
  scripts/extract_image_from_build_logs.sh
  scripts/gardener/aws/deprovision.sh
  scripts/gardener/aws/provision.sh
  scripts/ias/create-ias-app.sh
  scripts/ias/delete-ias-app.sh
  scripts/utils/log.sh
  scripts/utils/utils.sh
Labels: size/XL, lgtm, area/ci, cla: yes

#404 Updated backend switching job to use API Rules instead of port-forward
  .github/workflows/e2e-backend-switching-reuseable.yml
  hack/e2e/scripts/event_delivery_tests.sh
  hack/e2e/scripts/expose_epp_and_sink.sh
  scripts/cleanup_modules.sh
Labels: lgtm, area/ci, size/L, cla: yes

#406 Update eventing-publisher-proxy to image 1.0.1
  config/manager/manager.yaml
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#385 Remove lifecycle manager names from jobs
  .github/workflows/e2e.yml
Labels: size/XS, lgtm, area/ci, cla: yes

#407 Added backend-switching workflow for pull requests
  .github/workflows/e2e-backend-switching-reuseable.yml
  .github/workflows/e2e-k8s.yml
  .github/workflows/e2e.yml
  .github/workflows/pull-target-e2e.yml
  scripts/cleanup_modules.sh
  scripts/gardener/aws/provision.sh
Labels: lgtm, area/ci, size/L, cla: yes

#410 Bump eventing-manager image version for 1.1.0 release
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes

#408 Fixed wait-build-job for main branch
  .github/workflows/e2e-backend-switching-reuseable.yml
  .github/workflows/e2e.yml
  scripts/gardener/aws/deprovision.sh
  scripts/gardener/aws/provision.sh
Labels: size/M, lgtm, area/ci, cla: yes

#413 Use correct job name in release workflow
  .github/workflows/create-release.yml
Labels: size/XS, lgtm, area/ci, cla: yes

#415 fix broken release workflow
  .github/workflows/create-release.yml
Labels: size/XS, lgtm, area/ci, cla: yes

#414 use reusable linting workflow from kyma-project/eventing-tools
  .github/workflows/lint-go.yml
  .github/workflows/lint.yml
Labels: size/M, lgtm, area/ci, cla: yes

#416 fix the setting of env var PULL_BASE_REF in `Create release`
  .github/workflows/create-release.yml
Labels: size/XS, lgtm, area/ci, cla: yes

#417 Correct `manager.yaml` name
  README.md
  scripts/cleanup_modules.sh
  scripts/render_and_upload_manifests.sh
Labels: size/XS, lgtm, cla: yes

#418 Cherry pick changes to release workflow
  .github/workflows/create-release.yml
  README.md
  scripts/cleanup_modules.sh
  scripts/render_and_upload_manifests.sh
Labels: lgtm, size/S, area/ci, cla: yes

#420 Get random region for Gardener cluster in backend switching job and check for is-PR-approved
  .github/workflows/e2e-backend-switching-reuseable.yml
  .github/workflows/pull-target-e2e.yml
  scripts/gardener/aws/get_random_region.sh
  scripts/gardener/aws/provision.sh
  scripts/is_pr_approved.sh
  scripts/utils/utils.sh
Labels: lgtm, area/ci, size/L, cla: yes

#426 Fix `is-pr-approved` job
  .github/workflows/pull-target-e2e.yml
Labels: do-not-merge/hold, size/XS, lgtm, area/ci, cla: yes

#429 Updated comment in pull-target-e2e workflow
  .github/workflows/pull-target-e2e.yml
Labels: size/XS, lgtm, area/ci, cla: yes

#431 Make default CR have empty backend (#419)
  config/samples/default.yaml
  config/samples/default_nats.yaml
Labels: lgtm, size/S, cla: yes

#438 Fix broken links
  docs/user/tutorials/evnt-02-subs-with-multiple-filters.md
  docs/user/tutorials/evnt-03-type-cleanup.md
  docs/user/tutorials/evnt-04-change-max-in-flight-in-sub.md
  docs/user/tutorials/evnt-05-send-legacy-events.md
Labels: area/documentation, lgtm, size/S, cla: yes

#440 Update a link
  docs/user/README.md
Labels: size/XS, area/documentation, lgtm, cla: yes

#441 Update Eventing CR used in backend-switching job
  .github/workflows/e2e-backend-switching-reuseable.yml
Labels: size/XS, lgtm, area/ci, cla: yes

#439 Bumped dependencies
  go.mod
  go.sum
Labels: lgtm, size/S, cla: yes

#331 Rely on the NATS cluster connection status when reporting the Eventing CR status
  .golangci.yaml
  Dockerfile
  api/operator/v1alpha1/eventing_types.go
  api/operator/v1alpha1/eventing_types_test.go
  api/operator/v1alpha1/status.go
  api/operator/v1alpha1/status_test.go
  cmd/main.go
  cmd/main_test.go
  internal/connection/nats/builder.go
  internal/connection/nats/builder_test.go
  internal/connection/nats/connection.go
  internal/connection/nats/errors/errors.go
  internal/connection/nats/interface.go
  internal/connection/nats/mocks/builder.go
  internal/connection/nats/mocks/connection.go
  internal/controller/operator/eventing/controller.go
  internal/controller/operator/eventing/integrationtests/controller/integration_test.go
  internal/controller/operator/eventing/integrationtests/controllersinglecr/integration_test.go
  internal/controller/operator/eventing/integrationtests/controllerswitching/integration_test.go
  internal/controller/operator/eventing/integrationtests/nats_disabled/integration_test.go
  internal/controller/operator/eventing/integrationtests/natsconnection/integration_test.go
  internal/controller/operator/eventing/integrationtests/validation/integration_test.go
  internal/controller/operator/eventing/integrationtests/without_apirule_crd/integration_test.go
  internal/controller/operator/eventing/status.go
  internal/controller/operator/eventing/unit_test.go
  test/utils/integration/integration.go
Labels: kind/bug, lgtm, area/eventing, size/XXL, cla: yes

#444 Add missing steps
  docs/user/tutorials/evnt-02-subs-with-multiple-filters.md
  docs/user/tutorials/evnt-03-type-cleanup.md
  docs/user/tutorials/evnt-04-change-max-in-flight-in-sub.md
  docs/user/tutorials/evnt-05-send-legacy-events.md
Labels: area/documentation, size/M, lgtm, do-not-merge/missing-docs-review, cla: yes

#449 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: size/XS, lgtm, cla: yes

#451 docs: Fix spelling, incl EventING Publisher Proxy
  docs/user/README.md
  docs/user/evnt-architecture.md
  docs/user/evnt-event-names.md
  docs/user/resources/evnt-cr-subscription.md
  docs/user/troubleshooting/README.md
  docs/user/troubleshooting/evnt-04-free-jetstream-storage.md
  docs/user/tutorials/evnt-02-subs-with-multiple-filters.md
  docs/user/tutorials/evnt-03-type-cleanup.md
  docs/user/tutorials/evnt-04-change-max-in-flight-in-sub.md
  docs/user/tutorials/evnt-05-send-legacy-events.md
Labels: documentation, area/documentation, size/M, lgtm, area/eventing, cla: yes

#452 Remove module-template
  .gitignore
  Makefile
  module-config-template.yaml
  scripts/render_and_upload_manifests.sh
Labels: size/M, lgtm, cla: yes

#453 Fix md links
  docs/user/evnt-event-names.md
  docs/user/resources/evnt-cr-subscription.md
Labels: size/XS, area/documentation, lgtm, cla: yes

#401 Create Upgrade jobs for PR and main merge
  .github/workflows/e2e-upgrade-test-reusable.yaml
  .github/workflows/pull-e2e-upgrade-test.yaml
  .github/workflows/push-e2e-upgrade-test.yaml
  hack/ci/build-full-image-path.sh
Labels: lgtm, area/eventing, area/ci, size/L, cla: yes

#445 Changed image tag to main in sec-scanners-config
  sec-scanners-config.yaml
Labels: size/XS, lgtm, cla: yes
