Repository kyma-project/eventing-manager, pull requests merged in 2024-09, with the labels that each got.

#626 docs: update the contributing file
  CONTRIBUTING.md
Labels: size/XS, lgtm, cla: yes

#627 chore: update epp version to 1.1.0 in eventing-manager config
  config/manager/manager.yaml
Labels: size/XS, lgtm, cla: yes

#616 chore: bump dependencies
  Dockerfile
  go.mod
Labels: size/XS, lgtm, cla: yes

#638 fix: bump golint version to fix failing job
  .github/workflows/lint-go.yml
  .golangci.yaml
  Makefile
  hack/e2e/common/fixtures/fixtures.go
  internal/controller/eventing/subscription/jetstream/reconciler.go
  internal/controller/operator/eventing/integrationtests/validation/integration_test.go
  pkg/ems/api/events/client/client.go
  pkg/eventing/utils.go
  pkg/tracing/tracing.go
  pkg/tracing/tracing_test.go
  test/utils/utils.go
  testing/test_helpers.go
Labels: size/M, lgtm, area/ci, cla: yes

#637 chore: added github action based build jobs
  .github/workflows/pull-build-image.yaml
  .github/workflows/push-build-image.yaml
  .github/workflows/tag-build-image.yaml
  Dockerfile
Labels: size/M, lgtm, area/ci, cla: yes

#639 chore: replace prow build job waiting with github action
  .github/workflows/create-release.yml
  .github/workflows/e2e-upgrade-test-reusable.yaml
  .github/workflows/e2e.yml
  .github/workflows/pull-e2e-upgrade-test.yaml
  .github/workflows/pull-target-e2e.yml
  .github/workflows/push-e2e-upgrade-test.yaml
Labels: lgtm, area/ci, size/L, cla: yes

#641 chore: bump golang version to 1.23.1
  Dockerfile
  go.mod
Labels: size/XS, lgtm, cla: yes

#644 fix: remove prow reference
  docs/contributor/testing.md
Labels: area/documentation, lgtm, size/S, cla: yes

#646 chore: bump nats to 1.37.0
  api/operator/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  internal/controller/operator/eventing/mocks/typed_controller.go
  pkg/backend/jetstream/mocks/JetStreamContext.go
  pkg/backend/jetstream/stubs_test.go
  testing/test_helpers.go
Labels: size/M, lgtm, cla: yes
