Repository kyma-project/eventing-manager, pull requests merged in 2024-07, with the labels that each got.

#590 chore: bump dependencies
  api/operator/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  internal/connection/nats/mocks/connection.go
  internal/controller/eventing/subscription/eventmesh/reconciler.go
  internal/controller/eventing/subscription/jetstream/reconciler.go
  internal/controller/eventing/subscription/validator/mocks/SubscriptionValidator.go
  internal/controller/operator/eventing/controller.go
  internal/controller/operator/eventing/controller_test.go
  internal/controller/operator/eventing/mocks/controller.go
  internal/controller/operator/eventing/mocks/manager.go
  internal/controller/operator/eventing/mocks/nats_config_handler.go
  pkg/backend/jetstream/mocks/Backend.go
  pkg/backend/jetstream/mocks/JetStreamContext.go
  pkg/ems/api/events/client/mocks/PublisherManager.go
  pkg/eventing/mocks/manager.go
  pkg/k8s/mocks/client.go
  pkg/subscriptionmanager/manager/mocks/manager.go
  pkg/subscriptionmanager/mocks/manager_factory.go
  pkg/watcher/mocks/watcher.go
Labels: size/XL, lgtm, cla: yes

#596 deps(dependabot): upgrade modules for dependabot prs
  go.mod
  go.sum
Labels: lgtm, size/L, cla: yes

#601 docs: change enable and disable to add and delete in the eventing repo
  docs/user/01-manager.md
Labels: size/XS, area/documentation, lgtm, cla: yes

#599 chore: fix k8s compatibility test
  .github/workflows/k8s-compatibility-test.yml
  hack/ci/Makefile
  scripts/gardener/aws/provision.sh
Labels: lgtm, size/S, area/ci, cla: yes
