Repository kyma-project/eventing-manager, pull requests merged in 2024-08, with the labels that each got.

#606 deps: update build image
  Dockerfile
  go.mod
  go.sum
Labels: size/M, lgtm, cla: yes

#608 chore: bump go version to 1.22.6
  Dockerfile
  go.mod
Labels: size/XS, lgtm, cla: yes

#615 fix: link to default CR for NATS in docs
  docs/user/02-configuration.md
Labels: size/XS, area/documentation, lgtm, cla: yes

#614 chore: bump dependencies
  .gitignore
  .golangci.yaml
  Makefile
  config/crd/bases/eventing.kyma-project.io_subscriptions.yaml
  config/crd/bases/operator.kyma-project.io_eventings.yaml
  config/rbac/role.yaml
  go.mod
  go.sum
  hack/ci/Makefile
  internal/connection/nats/mocks/builder.go
  internal/connection/nats/mocks/connection.go
  internal/controller/eventing/subscription/eventmesh/reconciler.go
  internal/controller/eventing/subscription/jetstream/reconciler.go
  internal/controller/eventing/subscription/validator/mocks/SubscriptionValidator.go
  internal/controller/operator/eventing/controller.go
  internal/controller/operator/eventing/integrationtests/natsconnection/integration_test.go
  internal/controller/operator/eventing/mocks/controller.go
  internal/controller/operator/eventing/mocks/manager.go
  internal/controller/operator/eventing/mocks/nats_config_handler.go
  internal/controller/operator/eventing/mocks/typed_controller.go
  pkg/backend/jetstream/mocks/Backend.go
  pkg/backend/jetstream/mocks/JetStreamContext.go
  pkg/ems/api/events/client/mocks/PublisherManager.go
  pkg/eventing/mocks/manager.go
  pkg/k8s/mocks/client.go
  pkg/subscriptionmanager/manager/mocks/manager.go
  pkg/subscriptionmanager/mocks/manager_factory.go
  pkg/watcher/mocks/watcher.go
  scripts/gardener/aws/provision.sh
  test/utils/integration/integration.go
Labels: size/XL, lgtm, area/ci, cla: yes
