Repository kyma-project/eventing-manager, pull requests merged in 2024-03, with the labels that each got.

#519 chore: bump k8s version used in tests
  hack/ci/Makefile
Labels: size/XS, lgtm, cla: yes

#520 fix: Malformatted EventMesh Secret causes warning status
  .github/workflows/lint-go.yml
  internal/controller/operator/eventing/controller.go
  internal/controller/operator/eventing/controller_test.go
  internal/controller/operator/eventing/eventmesh.go
  internal/controller/operator/eventing/eventmesh_test.go
  internal/controller/operator/eventing/integrationtests/controller/integration_test.go
Labels: lgtm, area/ci, size/L, cla: yes

#524 chore: removed v1alpha1 subscription specifications from doc
  docs/user/resources/evnt-cr-subscription.md
Labels: area/documentation, size/M, lgtm, cla: yes

#526 Fix the link to Kyma Slack channels
  docs/user/troubleshooting/evnt-01-eventing-troubleshooting.md
Labels: size/XS, area/documentation, lgtm, kind/chore, cla: yes

#525 chore: add stale action
  .github/workflows/stale.yml
Labels: size/M, lgtm, area/ci, cla: yes

#530 chore: remove subscription v1alpha1 tests
  hack/e2e/common/eventing/testsubscriptioninfo.go
  hack/e2e/common/eventing/utils.go
  hack/e2e/common/fixtures/fixtures.go
  hack/e2e/common/k8s.go
  hack/e2e/common/testenvironment/test_environment.go
  hack/e2e/eventing/delivery/delivery_test.go
Labels: lgtm, size/L, cla: yes

#517 feat: remove v1alpha1 subscription
  .golangci.yaml
  api/eventing/v1alpha1/condition.go
  api/eventing/v1alpha1/condition_unit_test.go
  api/eventing/v1alpha1/fixtures_test.go
  api/eventing/v1alpha1/groupversion_info.go
  api/eventing/v1alpha1/subscription_conversion.go
  api/eventing/v1alpha1/subscription_conversion_unit_test.go
  api/eventing/v1alpha1/subscription_types.go
  api/eventing/v1alpha1/subscription_types_unit_test.go
  api/eventing/v1alpha1/subscription_webhook.go
  api/eventing/v1alpha1/zz_generated.deepcopy.go
  api/operator/v1alpha1/zz_generated.deepcopy.go
  cmd/main.go
  config/crd/bases/eventing.kyma-project.io_subscriptions.yaml
  config/samples/subscription_v1alpha1_js.yaml
  hack/e2e/common/eventing/testsubscriptioninfo.go
  hack/e2e/common/eventing/utils.go
  hack/e2e/common/fixtures/fixtures.go
  hack/e2e/common/testenvironment/test_environment.go
  hack/e2e/eventing/delivery/delivery_test.go
  internal/connection/nats/mocks/connection.go
  pkg/eventing/manager.go
  pkg/eventing/manager_test.go
  pkg/eventing/mocks/manager.go
  pkg/subscriptionmanager/eventmesh/eventmesh.go
  pkg/subscriptionmanager/jetstream/jetstream.go
  pkg/subscriptionmanager/mocks/manager_factory.go
  testing/test_helpers.go
Labels: area/documentation, lgtm, size/XXL, cla: yes

#540 docs: Fix link to Kyma Slack channel
  docs/user/troubleshooting/README.md
Labels: documentation, size/XS, lgtm, cla: yes

#541 docs: Apply markdowlint rules in the Eventing repository
  .markdownlint.yaml
  .markdownlintignore
  docs/contributor/installation.md
  docs/contributor/testing.md
  docs/user/02-configuration.md
  docs/user/troubleshooting/evnt-01-eventing-troubleshooting.md
  docs/user/troubleshooting/evnt-02-jetstream-troubleshooting.md
  docs/user/troubleshooting/evnt-03-type-collision.md
  docs/user/troubleshooting/evnt-05-fix-pending-messages.md
  docs/user/tutorials/evnt-03-type-cleanup.md
  docs/user/tutorials/evnt-04-change-max-in-flight-in-sub.md
  markdown_heading_capitalization.js
Labels: area/documentation, lgtm, size/L, cla: yes

#543 feature: added job to bump the rc-tag in the sec-scanners-config on main branch when creating release
  .github/workflows/create-release.yml
  hack/ci/await-pr-merge.sh
Labels: lgtm, area/ci, size/L, cla: yes
