Repository kyma-project/eventing-manager, pull requests merged in 2024-10, with the labels that each got.

#652 feat: add proper categories for CRDs
  api/eventing/v1alpha2/subscription_types.go
  api/operator/v1alpha1/eventing_types.go
  config/crd/bases/eventing.kyma-project.io_subscriptions.yaml
  config/crd/bases/operator.kyma-project.io_eventings.yaml
Labels: size/XS, lgtm, cla: yes

#657 chore: bump EPP version to 1.1.1
  config/manager/manager.yaml
Labels: size/XS, lgtm, cla: yes

#658 chore: bump EPP version to 1.1.1
  config/manager/manager.yaml
Labels: size/XS, area/documentation, lgtm, area/ci, cla: yes

#665 Revert kustomization.yaml
  config/manager/kustomization.yaml
Labels: size/XS, cla: yes

#666 Revert sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: size/XS, cla: yes

#671 docs: remove a broken link
  README.md
Labels: size/XS, lgtm, cla: yes

#676 chore: bump dependencies
  Dockerfile
  go.mod
  go.sum
  internal/connection/nats/mocks/connection.go
  internal/controller/eventing/subscription/validator/mocks/SubscriptionValidator.go
  internal/controller/operator/eventing/mocks/manager.go
  internal/controller/operator/eventing/mocks/nats_config_handler.go
  internal/controller/operator/eventing/mocks/typed_controller.go
  pkg/backend/jetstream/mocks/Backend.go
  pkg/backend/jetstream/mocks/JetStreamContext.go
  pkg/ems/api/events/client/mocks/PublisherManager.go
  pkg/eventing/mocks/manager.go
  pkg/k8s/mocks/client.go
  pkg/subscriptionmanager/manager/mocks/manager.go
  pkg/subscriptionmanager/mocks/manager_factory.go
  pkg/watcher/mocks/watcher.go
Labels: size/M, lgtm, cla: yes

#677 docs: update broken links
  docs/user/tutorials/evnt-02-subs-with-multiple-filters.md
  docs/user/tutorials/evnt-03-type-cleanup.md
  docs/user/tutorials/evnt-04-change-max-in-flight-in-sub.md
  docs/user/tutorials/evnt-05-send-legacy-events.md
Labels: size/XS, area/documentation, lgtm, cla: yes
